apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ditsignature
  namespace: default
  labels:
    app:  ditsignature
spec:
  selector:
    matchLabels:
      app: ditsignature
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ditsignature
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
      - name: arsoft-private-registry-pull-secret
      containers:
      - name:  ditsignature
        image:  hubcpa.ar.co.th:5000/lifelong-ditsignature:0.0.1-beta.1-alpha.26
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
        - name: spring.datasource.url
          value: "jdbc:postgresql://10.11.60.170:30432/testDB"
        - name: spring.datasource.username
          value: "testUser"
        - name: spring.datasource.password
          value: "testPassword"
        - name: activemq.broker.url
          value: tcp://10.11.60.170:31004
        - name: default.path
          value: /var/www/repo/application
        - name: logging.file.name
          value: /var/www/repo/application/logs/ditsignature.log        
        ports:
        - containerPort:  28084
          name:  ditsignature
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: application
          mountPath: /var/www/repo
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: application
          hostPath:
            path: /var/www/repo/application
          # persistentVolumeClaim:
          #   claimName: application-persistent-volume-claim
      restartPolicy: Always
      nodeSelector:
        env: sit
---
apiVersion: v1
kind: Service
metadata:
  name: ditsignature
  namespace: default
spec:
  type: NodePort
  selector:
    app: ditsignature
  ports:
  - port: 28080
    targetPort: 28080
    nodePort: 30205
---
