apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ditsignature
  namespace: default
  labels:
    app:  ditsignature
spec:
  selector:
    matchLabels:
      app: ditsignature
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ditsignature
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
      - name: private-swu-registry-pull-secret
      containers:
      - name:  ditsignature
        image:  hubcpa.swu.ac.th:30005/lifelong-ditsignature:0.0.1-beta.2-alpha.17
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
        - name: spring.datasource.url
          value: "jdbc:postgresql://lb-postgresdb-uat:5432/swuuat"
        - name: spring.datasource.username
          value: "uatuser"
        - name: spring.datasource.password
          value: "uatpassword"
        - name: activemq.broker.url
          value: tcp://activemq:61616
        - name: default.path
          value: /var/www/repo/application
        - name: logging.file.name
          value: /var/www/repo/application/logs/ditsignature.log
        - name: app.config.mail.url
          value: http://mailgateway:28085/mailgateway
        - name: app.config.sign.url
          value: http://digitalsignature:28084/digitalsignature
        - name: spring.boot.admin.client.url
          value: http://lifelong-admin-sv:9011
        - name: spring.boot.admin.client.instance.service-base-url
          value: http://ditsignature:28084
        - name: EUREKA_SERVICE_URL
          value: http://lifelong-admin-eureka:9002
        ports:
        - containerPort:  28084
          name:  ditsignature
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: application
          mountPath: /var/www/repo
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: application
          hostPath:
            path: /var/www/repo/application
          # persistentVolumeClaim:
          #   claimName: application-persistent-volume-claim
      restartPolicy: Always
      # nodeSelector:
      #   env: sit
---
apiVersion: v1
kind: Service
metadata:
  name: ditsignature-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: ditsignature
  ports:
  - port: 28084
    targetPort: 28084
    nodePort: 30204
---
apiVersion: v1
kind: Service
metadata:
  name: ditsignature
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ditsignature
  ports:
  - port: 28084
    targetPort: 28084
