/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CoursepublicLogData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** FK (coursepublic_main) */
    coursepublicId?: number;
    /** PK */
    coursepublicLogId?: number;
    /** สถานะเปิดรอบหลักสูตร */
    coursepublicStatus?: number;
    /** id ผู้บันทึก */
    createById?: number;
    /** วันเวลาที่บันทึก */
    createTimestamp?: number;
    cancelReason?:string;
    first?: number;
    mode?: string;
    rowNum?: number;
    size?: number;
    createDate?: Date;

    statusnameTh?: string;
    statusnameEn?: string;
    fullnameTh?: string;
    fullnameEn?: string;

}
