/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CoursepublicGradeData {
    /** PK */
    coursepublicGradeId?: number;
    /** Course public id */
    coursepublicId?: number;
    first?: number;
    /** Grade symbol */
    gradeSymbol?: string;
    /** member id */
    memberId?: number;
    mode?: string;
    /** Pass status */
    passStatus?: boolean;
    rowNum?: number;
    /** Score */
    score?: number;
    /** Score max */
    scoreMax?: number;
    /** Score min */
    scoreMin?: number;
    size?: number;
    createById?:number;
    createDate?:Date;
}
