/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CourseOccupationData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** FK (course_main) */
    courseId?: number;
    /** PK */
    courseOccupationId?: number;
    first?: number;
    mode?: string;
    /** FK (mas_occupation) */
    occupationId?: number;
    rowNum?: number;
    size?: number;
}
