/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CourseTargetData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** FK (course_main) */
    courseId?: number;
    /** PK */
    courseTargetId?: number;
    first?: number;
    mode?: string;
    rowNum?: number;
    size?: number;
    /** กลุ่มเป้าหมาย LOOKUP (30002000)  */
    targetGroupId?: number;
}
