/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CourseActivityMethodData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** PK */
    courseActivityMethodId?: number;
    /** FK (course_main) */
    courseId?: number;
    /** รายละเอียดเพิ่มเติม */
    courseMethodDetail?: string;
    /** FK (mas_course_method) */
    courseMethodId?: number;
    first?: number;
    mode?: string;
    rowNum?: number;
    size?: number;
}
