/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CourseScloData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** FK (course_main) */
    courseId?: number;
    /** รหัส SCLO */
    courseScloCode?: string;
    /** ผลลัพธ์การเรียนรู้ของหลักสูตรอบรมระยะสั้น */
    courseScloDesc?: string;
    /** PK */
    courseScloId?: number;
    first?: number;
    mode?: string;
    rowNum?: number;
    size?: number;
}
