apiVersion: apps/v1
kind: Deployment
metadata:
  name:  lifelong-operation-ui
  namespace: default
  labels:
    app:  lifelong-operation-ui
spec:
  selector:
    matchLabels:
      app: lifelong-operation-ui
  replicas: 2
  template:
    metadata:
      labels:
        app:  lifelong-operation-ui
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
      - name: arsoft-private-registry-pull-secret
      containers:
      - name:  lifelong-operation-ui
        image:  hubcpa.ar.co.th:5000/lifelong-operation-ui:0.0.1-beta.2-alpha.18
        ports:
        - containerPort:  80
          name:  lifelongport
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
      restartPolicy: Always
      nodeSelector:
        env: sit
---
apiVersion: v1
kind: Service
metadata:
  name: np-lifelong-operation-ui
  namespace: default
spec:
  type: NodePort
  selector:
    app: lifelong-operation-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30102
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: clst-lifelong-operation-ui
#   namespace: ingress-nginx
#   labels:
#     app:  clst-lifelong-operation-ui
# spec:
#   type: ClusterIP
#   selector:
#     app: lifelong-operation-ui
#   ports:
#   - port: 80
#     targetPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service-tcp
#   namespace: ingress-nginx
#   labels:
#     run: nginx-service-tcp
# spec:
#   ports:
#   - port: 80
#     protocol: TCP
#   selector:
#     app: lifelong-operation-ui
