apiVersion: apps/v1
kind: Deployment
metadata:
  name:  student-api
  namespace: default
  labels:
    app:  student-api
spec:
  selector:
    matchLabels:
      app: student-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  student-api
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
      - name: private-swu-registry-pull-secret
      containers:
      - name:  student-api
        image:  hubcpa.swu.ac.th:30005/lifelong-student-api:0.0.1-beta.2-alpha.17
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
        - name: spring.jpa.hibernate.ddl-auto
          value: update
        - name: spring.datasource.url
          value: "jdbc:postgresql://postgresdb-uat:5432/swuuat"
        - name: spring.datasource.username
          value: "uatuser"
        - name: spring.datasource.password
          value: "uatpassword"
        - name: spring.datasource.hikari.maximum-pool-size
          value: "50"
        - name: spring.datasource.hikari.connectionTestQuery
          value: "SELECT 1"
        - name: spring.datasource.hikari.connection-timeout
          value: "300000"
        - name: spring.datasource.hikari.idle-timeout
          value: "15000"
        - name: spring.datasource.hikari.max-lifetime
          value: "35000"
        - name: spring.datasource.hikari.validationTimeout
          value: "300000"
        - name: default.path
          value: /var/www/repo/application
        - name: logging.file.name
          value: /var/www/repo/application/logs/studentapi.log
        - name: app.client.host
          value: https://uat-lifelong.swu.ac.th
        - name: activemq.broker.url
          value: tcp://activemq:61616
        - name: app.config.moodle.url
          value: https://course.lifelong.swu.ac.th/webservice/rest/server.php
        - name: security.ldap.url
          value: ldap://ldap.swu.ac.th:389
        - name: security.ldap.base
          value: dc=swu,dc=ac,dc=th
        ports:
        - containerPort:  28081
          name:  operation-api
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: application
          mountPath: /var/www/repo
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: application
          hostPath:
            path: /var/www/repo/application
          # persistentVolumeClaim:
          #   claimName: application-persistent-volume-claim
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: np-lifelong-student-api
  namespace: default
spec:
  type: NodePort
  selector:
    app: student-api
  ports:
  - port: 28081
    targetPort: 28081
    nodePort: 30112
---