apiVersion: apps/v1
kind: Deployment
metadata:
  name:  admin-sv
  namespace: default
  labels:
    app:  admin-sv
spec:
  selector:
    matchLabels:
      app: admin-sv
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  admin-sv
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
      - name: private-swu-registry-pull-secret
      containers:
      - name:  admin-sv
        image:  hubcpa.swu.ac.th:30005/lifelong-admin-sv:0.0.1
        imagePullPolicy: Always
        # resources: 
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
        # - name: spring.jpa.hibernate.ddl-auto
        #   value: update
        # - name: spring.datasource.url
        #   value: "jdbc:postgresql://postgresdb-uat:5432/swuuat"
        # - name: spring.datasource.username
        #   value: "uatuser"
        # - name: spring.datasource.password
        #   value: "uatpassword"
        # - name: activemq.broker.url
        #   value: tcp://activemq:61616
        # - name: java.awt.headless
        #   value: "true"
        # - name: default.path
        #   value: /var/www/repo/application
        - name: logging.file.name
          value: /var/www/repo/application/logs/admin-sv.log
        ports:
        - containerPort:  9011
          name:  admin-sv
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: application
          mountPath: /var/www/repo
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: application
          hostPath:
            path: /var/www/repo/application
          # persistentVolumeClaim:
          #   claimName: application-persistent-volume-claim
      restartPolicy: Always      
---
apiVersion: v1
kind: Service
metadata:
  name: lifelong-admin-sv-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: admin-sv
  ports:
  - port: 9011
    targetPort: 9011
    nodePort: 30301
---
apiVersion: v1
kind: Service
metadata:
  name: lifelong-admin-sv
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: admin-sv
  ports:
  - port: 9011
    targetPort: 9011
