apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  namespace: default
  labels:
    app:  backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  backend
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
      - name: private-swu-registry-pull-secret
      containers:
      - name:  backend
        image:  hubcpa.swu.ac.th:30005/lifelong-backend:0.0.1-beta.2-alpha.17
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
        - name: spring.datasource.url
          value: "jdbc:postgresql://lb-postgresdb-uat:5432/swuuat"
        - name: spring.datasource.username
          value: "uatuser"
        - name: spring.datasource.password
          value: "uatpassword"
        - name: spring.jpa.properties.hibernate.dialect.flushMode
          value: ALWAYS
        - name: spring.jpa.properties.org.hibernate.flushMode
          value: ALWAYS
        - name: spring.datasource.hikari.maximum-pool-size
          value: "4000"
        - name: spring.datasource.hikari.connectionTestQuery
          value: "SELECT 1"
        - name: spring.datasource.hikari.connection-timeout
          value: "100000"
        - name: spring.datasource.hikari.idle-timeout
          value: "5000"
        - name: spring.datasource.hikari.max-lifetime
          value: "5000"
        - name: spring.datasource.hikari.validationTimeout
          value: "300000"
        - name: activemq.broker.url
          value: tcp://activemq:61616
        - name: default.path
          value: /var/www/repo/application
        - name: logging.file.name
          value: /var/www/repo/application/logs/backend.log
        - name: spring.jpa.hibernate.ddl-auto
          value: update
        - name: app.config.mailgateway.url
          value: http://emailgateway:28086/mailgateway
        - name: app.config.sign.url
          value: http://ditsignature:28084/digitalsignature
        - name: app.config.env.url
          value: https://uat-lifelong.swu.ac.th
        - name: app.config.env.urladmin
          value: https://uat-lifelong-admin.swu.ac.th
        - name: sftp.buasri.host
          value: "10.1.5.11"
        - name: sftp.buasri.port
          value: "22"
        - name: sftp.buasri.username
          value: creditbank
        - name: sftp.buasri.password
          value: swug8ifb9bank
        - name: sftp.buasri.default.path
          value: /home/buasri/creditbank/
        - name: sftp.buasri.sessionTimeout
          value: "15000"
        - name: sftp.buasri.channelTimeout
          value: "15000"
        - name: api.officer.basic.auth.domain
          value: https://api.swu.ac.th/lifelong/Officer/GetData
        - name: api.department.basic.auth.domain
          value: https://api.swu.ac.th/lifelong/Department/GetData
        - name: api.officer.basic.auth.username
          value: "661003"
        - name: api.officer.basic.auth.password
          value: Ra6azemefUmak
        - name: api.officer.basic.auth.apikey
          value: j7yedekayawuT
        - name: app.config.moodle.url
          value: https://course.lifelong.swu.ac.th/webservice/rest/server.php
        - name: security.ldap.url
          value: ldap://ldap.swu.ac.th:389
        - name: security.ldap.base
          value: dc=swu,dc=ac,dc=th
        ports:
        - containerPort:  28080
          name:  backend
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: application
          mountPath: /var/www/repo
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: application
          hostPath:
            path: /var/www/repo/application
          # persistentVolumeClaim:
          #   claimName: application-persistent-volume-claim
      restartPolicy: Always
      # nodeSelector:
      #   env: sit
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 28080
    targetPort: 28080
    nodePort: 30205
---
