apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  namespace: default
  labels:
    app:  backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  backend
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
      - name: arsoft-private-registry-pull-secret
      containers:
      - name:  backend
        image:  hubcpa.ar.co.th:5000/lifelong-backend:0.0.1-beta.2-alpha.17
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
        - name: spring.datasource.url
          value: "jdbc:postgresql://10.11.60.170:30432/testDB"
        - name: spring.datasource.username
          value: "testUser"
        - name: spring.datasource.password
          value: "testPassword"
        - name: activemq.broker.url
          value: tcp://10.11.60.170:31004
        - name: default.path
          value: /var/www/repo/application
        - name: logging.file.name
          value: /var/www/repo/application/logs/backend.log
        - name: app.config.mail.url
          value: http://mailgateway:28085/mailgateway
        - name: app.config.sign.url
          value: http://digitalsignature:28084/digitalsignature
        - name: app.config.env.url
          value: https://localhost
        - name: sftp.buasri.host
          value: "10.11.60.206"
        - name: sftp.buasri.port
          value: "22"
        - name: sftp.buasri.username
          value: administrator
        - name: sftp.buasri.password
          value: 1qaz2wsx
        - name: sftp.buasri.default.path
          value: /home/administrator
        - name: sftp.buasri.sessionTimeout
          value: "15000"
        - name: sftp.buasri.channelTimeout
          value: "15000"
        - name: api.officer.basic.auth.domain
          value: https://api.swu.ac.th/lifelong/Officer/GetData
        - name: api.department.basic.auth.domain
          value: https://api.swu.ac.th/lifelong/Department/GetData
        - name: api.officer.basic.auth.username
          value: "661003"
        - name: api.officer.basic.auth.password
          value: Ra6azemefUmak
        - name: api.officer.basic.auth.apikey
          value: j7yedekayawuT
        ports:
        - containerPort:  28080
          name:  backend
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: application
          mountPath: /var/www/repo
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: application
          hostPath:
            path: /var/www/repo/application
          # persistentVolumeClaim:
          #   claimName: application-persistent-volume-claim
      restartPolicy: Always
      # nodeSelector:
      #   env: sit
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 28080
    targetPort: 28080
    nodePort: 30205
---
