/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from './masBankAccountData';
export * from './masBankBranchData';
export * from './masBankChargeAttachData';
export * from './masBankChargeData';
export * from './masBankData';
export * from './masCourseTypeData';
export * from './masDepartmentData';
export * from './masGeneralSkillData';
export * from './masOccupationData';
export * from './masOccupationGroupData';
export * from './masOccupationSkillData';
export * from './masPersonalData';
export * from './masSharePercentAttachData';
export * from './masSharePercentData';
export * from './masSharePercentHistoryData';
export * from './notiInfoData';
export * from './sysProgressData';
export * from './masGeneralSkillLevelData';
