/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MasBankBranchData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** รหัสสาขา */
    bankBranchCode: string;
    /** pk สาขาธนาคาร */
    bankBranchId?: number;
    /** ชื่อสาขา (ภาษาอังกฤษ) */
    bankBranchNameEn: string;
    /** ชื่อสาขา (ภาษาไทย) */
    bankBranchNameTh: string;
    /** fk ธนาคาร */
    bankId: number;
    /** custom ชื่อธนาคาร (ภาษาอังกฤษ) */
    bankNameEn?: string;
    /** custom ชื่อธนาคาร (ภาษาไทย) */
    bankNameTh?: string;
    first?: number;
    mode?: string;
    rowNum?: number;
    size?: number;
}
