/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MasBankAccountData {
    /** ชื่อบัญชี (ภาษาอังกฤษ) */
    accountNameEn: string;
    /** ชื่อบัญชี (ภาษาไทย) */
    accountNameTh: string;
    /** เลขที่บัญชี */
    accountNo: string;
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** PK */
    bankAccountId?: number;
    /** หมายเหตุ */
    bankAccountNote?: string;
    /** สาขา */
    bankBranchId?: number;
    /** custom ชื่อสาขาธนาคาร (ภาษาอังกฤษ) */
    bankBranchNameEn?: string;
    /** custom ชื่อสาขาธนาคาร (ภาษาไทย) */
    bankBranchNameTh?: string;
    /** ธนาคาร */
    bankId?: number;
    /** custom ชื่อธนาคาร (ภาษาอังกฤษ) */
    bankNameEn?: string;
    /** custom ชื่อธนาคาร (ภาษาไทย) */
    bankNameTh?: string;
    /** Biller ID */
    billerId?: string;
    /** Company ID */
    companyId?: string;
    first?: number;
    mode?: string;
    rowNum?: number;
    size?: number;
}
