/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MasCourseTypeData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** การเทียบเคียงหลักสูตร */
    courseMappingStatus?: boolean;
    /** รหัสประเภทหลักสูตร */
    courseTypeCode?: string;
    /** ประเภทหลักสูตร */
    courseTypeId?: number;
    /** ชื่อประเภทหลักสูตร (อังกฤษ) */
    courseTypeNameEn?: string;
    /** ชื่อประเภทหลักสูตร (ภาษาไทย) */
    courseTypeNameTh?: string;
    /** เรียงลำดับ */
    courseTypeOrder?: number;
    first?: number;
    mode?: string;
    rowNum?: number;
    size?: number;
    filename?: string;
    module?: number;
    prefix?: string;
}
