/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MasOccupationGroupData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    first?: number;
    mode?: string;
    /** รหัสกลุ่มอาชีพ */
    occupationGroupCode?: string;
    /** pk กลุ่มอาชีพ */
    occupationGroupId?: number;
    /** ชื่อกลุ่มอาชีพ (ภาษาอังกฤษ) */
    occupationGroupNameEn: string;
    /** ชื่อกลุ่มอาชีพ (ภาษาไทย) */
    occupationGroupNameTh: string;
    rowNum?: number;
    size?: number;
}
