/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * custom ประเภททักษะ (ภาษาอังกฤษ)
 */
export interface MasOccupationSkillData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    first?: number;
    /** FK ทักษะ mas_general_skill */
    generalSkillId?: number;
    /** custom ทักษะ (ภาษาอังกฤษ)  */
    generalSkillNameEn?: string;
    /** custom ทักษะ (ภาษาไทย)  */
    generalSkillNameTh?: string;
    /** custom ระดับ (ภาษาอังกฤษ)  */
    levelNameEn?: string;
    /** custom ระดับ (ภาษาไทย)  */
    levelNameTh?: string;
    mode?: string;
    /** PK */
    occSkillId?: number;
    /** ระดับ LOOKUP (30011000)  */
    occSkillLevel?: number;
    /** FK อาชีพ mas_occupation */
    occupationId?: number;
    rowNum?: number;
    size?: number;
}
