/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MasPersonalData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** Buasri ID */
    buasriId?: string;
    /** รหัสส่วนงาน/คณะ */
    depCodeLevel1?: string;
    /** fk หน่วยงานย่อย */
    depCodeLevel2?: number;
    /** custom ใช้สำหรับค้นหา หน่วยงาน */
    // depId?: number;
    /** fk ส่วนงาน/คณะ */
    depIdLevel1?: number;
    /** custom ชื่อส่วนงาน/คณะ (อังกฤษ) */
    depNameLv1En?: string;
    /** custom ชื่อส่วนงาน/คณะ (ไทย) */
    depNameLv1Th?: string;
    /** custom ชื่อหน่วยงานย่อย (อังกฤษ) */
    depNameLv2En?: string;
    /** custom ชื่อหน่วยงานย่อย (ไทย) */
    depNameLv2Th?: string;
    /** อีเมลล์ */
    email?: string;
    first?: number;
    /** ชื่อ (อังกฤษ) */
    firstnameEn?: string;
    /** ชื่อ (ไทย) */
    firstnameTh?: string;
    /** custom ใช้สำหรับค้นหา ชื่อ-สกุล */
    fullname?: string;
    /** นามสกุล (อังกฤษ) */
    lastnameEn?: string;
    /** นามสกุล (ไทย) */
    lastnameTh?: string;
    /** ชื่อกลาง (อังกฤษ) */
    middlenameEn?: string;
    /** ชื่อกลาง (ไทย) */
    middlenameTh?: string;
    mode?: string;
    /** PK */
    personalId?: number;
    /** ประเภทปฏิบัติการ */
    personalLine?: string;
    /** filename */
    personalPhotoPath?: string;
    /** ประเภทบุคลากร LOOKUP (30020000)  */
    personalType?: number;
    /** custom ชื่อประเภทบุคลากร (อังกฤษ) */
    personalTypeEn?: string;
    /** custom ชื่อประเภทบุคลากร (ไทย) */
    personalTypeTh?: string;
    /** ตำแหน่ง (อังกฤษ) */
    positionEn?: string;
    /** ตำแหน่ง (ไทย) */
    positionTh?: string;
    /** คำนำหน้า (อังกฤษ) */
    prefixEn?: string;
    /** ชื่อย่อคำนำหน้า (อังกฤษ) */
    prefixShortEn?: string;
    /** ชื่อย่อคำนำหน้า (ไทย) */
    prefixShortTh?: string;
    /** คำนำหน้า (ไทย) */
    prefixTh?: string;
    rowNum?: number;
    size?: number;
    /** รหัสสถานะ */
    statusId?: string;
    /** สถานภาพ (อังกฤษ) */
    statusNameEn?: string;
    /** สถานภาพ (ไทย) */
    statusNameTh?: string;
    module?: number;
    prefix?: string;
    coursepublicStatus?: number;
}
