/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MasSharePercentAttachData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** fk (depId) */
    depId?: number;
    /** Link */
    fileLink: string;
    /** ชื่อไฟล์ */
    fileName: string;
    first?: number;
    mode?: string;
    rowNum?: number;
    /** PK auto run (share_percent_attach_id)  */
    sharePercentAttachId?: number;
    size?: number;
}
