/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from './reportCanceledCourseData';
export * from './reportCourseEnrollmentData';
export * from './reportCoursePaymentData';
export * from './reportDepartmentIncomeData';
export * from './reportEnrollmentAndPaymentData';
export * from './reportEnrollmentListData';
export * from './reportOfferedCourseData';
