/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ReportCanceledCourseData {
    coursepublicId?: number;
    requestCancelDate?: string;
    requestCancelDateList?: string[];
    courseCode?: string;
    coursepublicStatus?: number;
    coursepublicStatusEn?: string;
    coursepublicStatusTh?: string;
    first?: number;
    fullCourseEn?: string;
    fullCourseTh?: string;
    memberCount?: number;
    mode?: string;
    paymentCount?: number;
    publicNameEn?: string;
    publicNameTh?: string;
    rowNum?: number;
    size?: number;
    courseGeneration?: number;
    remainAmount?: number;
    registerCount?: number;
}
