/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ReportOfferedCourseData {
    countRound?: number;
    courseCode?: string;
    courseNameEn?: string;
    courseNameTh?: string;
    courseStatus?: number;
    dateSend?: string;
    depId?: number;
    depNameShortEn?: string;
    depNameShortTh?: string;
    first?: number;
    fullCourseEn?: string;
    fullCourseTh?: string;
    mode?: string;
    rowNum?: number;
    size?: number;
    statusEn?: string;
    statusTh?: string;
    userSendEn?: string;
    userSendTh?: string;
}
