/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ReportCourseEnrollmentData {
    completedAmount?: number;
    courseCode?: string;
    courseStatus?: number;
    first?: number;
    fullCourseEn?: string;
    fullCourseTh?: string;
    maxEnroll?: number;
    mode?: string;
    publicNameEn?: string;
    publicNameTh?: string;
    registerAmount?: number;
    rowNum?: number;
    size?: number;
    statusEn?: string;
    statusTh?: string;
}
