/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ReportEnrollmentAndPaymentData {
    courseCode?: string;
    depId?: number;
    depNameShortEn?: string;
    depNameShortTh?: string;
    first?: number;
    fullCourseEn?: string;
    fullCourseTh?: string;
    mode?: string;
    publicNameEn?: string;
    publicNameTh?: string;
    registerCount?: number;
    remainAmount?: number;
    rowNum?: number;
    size?: number;
}
