/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * การอนุญาต
 */
export interface AllMenuData {
    activeFlag?: boolean;
    link?: string;
    menuCode?: string;
    menuId?: number;
    menuType?: string;
    name?: string;
    orderNumber?: number;
    parentId?: number;
    permissionId?: number;
    showNameKey?: string;
}
