/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * การอนุญาต
 */
export interface AutPermissionData {
    first?: number;
    /** FK (aut_menu) */
    menuId?: number;
    mode?: string;
    /** PK */
    permissionId?: number;
    /** FK (aut_role) */
    roleId?: number;
    rowNum?: number;
    size?: number;
}
