export type MODE_PAGE = 'LIST' | 'CREATE' | 'EDIT' | 'VIEW' | 'APPROVE' | 'REQUEST'

export type MODE_PAGE_CHILDE = 'CREATE_CHILDE' | 'EDIT_CHILDE' | 'VIEW_CHILDE' | 'MAIN'

export type MODE_PAGE_CHILDE_2 = 'CREATE_CHILDE_2' | 'EDIT_CHILDE_2' | 'VIEW_CHILDE_2' | 'MAIN_1'

export type MODE_PAGE_CHILDE_3 = 'CREATE_CHILDE_3' | 'EDIT_CHILDE_3' | 'VIEW_CHILDE_3' | 'MAIN_2'

export enum COURSE_PAGE {
    /** general information */
    COURSE_COMPARISON,
    DOCUMENTS_AND_MORE,
    RELATED_AGENCIES_OR_ESTABLISHMENTS,
    TEACHING_FORMAT,
    DETAIL_OF_THE_SHORT_TRAINING_COURSE,
    INDUSTRY_GROUP_OR_TARGET_GROUP,
    RESPONSIBLE_PERSON,
    /** lerning outcomes */
    EXPECTED_LEARNING_OUTCOMES,
    LEARNING_MANAGEMENT_PROCESS,
    LEARNING_OUTCOMES,
    /** approval documents */
    COURSE_APPROVAL_DOCUMENTS
}

export enum COURSE_ROUND_PAGE {
    ROUND_OPEN_COURSE_ROUND,
    ROUND_LOCATION_AND_STUDY_LOCATION,
    ROUND_INSTRUCTOR,
    ROUND_TEACHING_DOCUMENTS,
    ROUND_EXPENSES_AND_SHARE_OF_REGISTRATION_FEES,
    ROUND_ACCOMPANYING_VIDEO,
    ROUND_THUMBNAIL,
    ROUND_OTHER_ILLUSTRATIONS
}

export enum IMPORT_PAYMENT_PAGE {
    IMPORT_PAYMENT_FIRST,
    IMPORT_PAYMENT_SECOND,
    IMPORT_PAYMENT_THIRD,
    IMPORT_PAYMENT_FOURTH
}
