apiVersion: apps/v1
kind: Deployment
metadata:
  name:  emailgateway
  namespace: default
  labels:
    app:  emailgateway
spec:
  selector:
    matchLabels:
      app: emailgateway
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  emailgateway
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
      - name: private-swu-registry-pull-secret
      containers:
      - name:  emailgateway
        image:  hubcpa.swu.ac.th:30005/lifelong-emailgateway:0.0.1-beta.1-alpha.29
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
        - name: server.port
          value: '28086'
        - name: spring.datasource.url
          value: "jdbc:postgresql://lb-postgresdb-uat:5432/swuuat"
        - name: spring.datasource.username
          value: "uatuser"
        - name: spring.datasource.password
          value: "uatpassword"
        - name: activemq.broker.url
          value: tcp://activemq:61616
        - name: default.path
          value: /var/www/repo/application
        - name: logging.file.name
          value: /var/www/repo/application/logs/emailgateway.log
        - name: spring.mail.host
          value: smtp.gmail.com
        - name: spring.mail.port
          value: '587'
        - name: spring.mail.username
          value: noreply-lifelong@g.swu.ac.th
        - name: spring.mail.password
          value: krfabowpvibluzid
        ports:
        - containerPort:  28086
          name:  emailgateway
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: application
          mountPath: /var/www/repo
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: application
          hostPath:
            path: /var/www/repo/application
          # persistentVolumeClaim:
          #   claimName: application-persistent-volume-claim
      restartPolicy: Always
      # nodeSelector:
      #   env: sit
---
apiVersion: v1
kind: Service
metadata:
  name: emailgateway-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: emailgateway
  ports:
  - port: 28086
    targetPort: 28086
    nodePort: 30206
---
apiVersion: v1
kind: Service
metadata:
  name: emailgateway
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: emailgateway
  ports:
  - port: 28086
    targetPort: 28086
