/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TmpFinanceImportDetailData {
    /** สถานะการใช้งาน */
    activeFlag?: boolean;
    /** ที่อยู่ */
    address?: string;
    /** Fk (courserpublic_main) */
    coursepublicId?: number;
    /** PK */
    detailId?: number;
    /** สถานะรายการ pass, fail, miss */
    detailStatus?: string;
    /** อีเมล */
    email?: string;
    /** ข้อความ Error */
    errorMessage?: string;
    first?: number;
    /** ชื่อ (อังกฤษ) */
    firstnameEn?: string;
    /** ชื่อ (ภาษาไทย) */
    firstnameTh?: string;
    /** นามสกุล (อังกฤษ) */
    lastnameEn?: string;
    /** นามสกุล (ภาษาไทย) */
    lastnameTh?: string;
    /** id card */
    memberIdCard?: string;
    /** ชื่อผู้เรียน */
    memberName?: string;
    mode?: string;
    /** ที่อยู่นิติบุคคล */
    orgAddress?: string;
    /** หมายเลขนิติบุคคล */
    orgLegalCode?: string;
    /** ชื่อนิติบุคคล */
    orgName?: string;
    /** จำนวนเงินที่ชำระ */
    payAmount?: number;
    /** วันที่ชำระเงิน */
    payDatetime?: string;
    /** คำนำหน้า */
    prefix?: string;
    /** คำนำหน้า sys_prefixname */
    prefixnameId?: number;
    rowNum?: number;
    size?: number;
    /** Fk (tmp_finance_import_log) */
    tmpImpId?: number;
}
