/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { ResponseListIf, ResponseOneIf } from 'src/app/models/common';
import type {
    FinanceImportDetailData,
    FinanceImportLogData,
    FinancePaymentData,
    FinanceReceiptConfigData,
    TmpFinanceImportDetailData,
    TmpFinanceImportLogData
} from 'src/app/models/financial-management';
import { environment } from 'src/environments/environment';

@Injectable({ providedIn: 'root' })
export class FinancialManagementService {
    constructor(private http: HttpClient) {}

    getTmpFinanceImportLog(tmpImpId: number): Observable<ResponseOneIf<TmpFinanceImportLogData>> {
        return this.http.get<ResponseOneIf<TmpFinanceImportLogData>>(
            `${environment.apiUrl}/financial-management/tmp-finance-import-log/${tmpImpId}`
        );
    }
    putTmpFinanceImportLog(
        tmpImpId: number,
        tmpFinanceImportLogData: TmpFinanceImportLogData
    ): Observable<ResponseOneIf<TmpFinanceImportLogData>> {
        return this.http.put<ResponseOneIf<TmpFinanceImportLogData>>(
            `${environment.apiUrl}/financial-management/tmp-finance-import-log/${tmpImpId}`,
            tmpFinanceImportLogData
        );
    }
    putTmpFinanceImportLogCommit(
        tmpImpId: number,
        tmpFinanceImportLogData: TmpFinanceImportLogData
    ): Observable<ResponseOneIf<TmpFinanceImportLogData>> {
        return this.http.put<ResponseOneIf<TmpFinanceImportLogData>>(
            `${environment.apiUrl}/financial-management/tmp-finance-import-log/commit/${tmpImpId}`,
            tmpFinanceImportLogData
        );
    }
    getTmpFinanceImportDetail(detailId: number): Observable<ResponseOneIf<TmpFinanceImportDetailData>> {
        return this.http.get<ResponseOneIf<TmpFinanceImportDetailData>>(
            `${environment.apiUrl}/financial-management/tmp-finance-import-detail/${detailId}`
        );
    }
    putTmpFinanceImportDetail(
        detailId: number,
        tmpFinanceImportDetailData: TmpFinanceImportDetailData
    ): Observable<ResponseOneIf<TmpFinanceImportDetailData>> {
        return this.http.put<ResponseOneIf<TmpFinanceImportDetailData>>(
            `${environment.apiUrl}/financial-management/tmp-finance-import-detail/${detailId}`,
            tmpFinanceImportDetailData
        );
    }
    getFinanceReceiptConfig(): Observable<ResponseOneIf<FinanceReceiptConfigData>> {
        return this.http.get<ResponseOneIf<FinanceReceiptConfigData>>(
            `${environment.apiUrl}/financial-management/finance-receipt-config`
        );
    }
    putFinanceReceiptConfig(
        receiptConfigId: number,
        financeReceiptConfigData: FinanceReceiptConfigData
    ): Observable<ResponseOneIf<FinanceReceiptConfigData>> {
        return this.http.put<ResponseOneIf<FinanceReceiptConfigData>>(
            `${environment.apiUrl}/financial-management/finance-receipt-config/${receiptConfigId}`,
            financeReceiptConfigData
        );
    }
    getFinanceImportDetail(detailId: number): Observable<ResponseOneIf<FinanceImportDetailData>> {
        return this.http.get<ResponseOneIf<FinanceImportDetailData>>(
            `${environment.apiUrl}/financial-management/finance-import-detail/${detailId}`
        );
    }
    putFinanceImportDetail(
        detailId: number,
        financeImportDetailData: FinanceImportDetailData
    ): Observable<ResponseOneIf<FinanceImportDetailData>> {
        return this.http.put<ResponseOneIf<FinanceImportDetailData>>(
            `${environment.apiUrl}/financial-management/finance-import-detail/${detailId}`,
            financeImportDetailData
        );
    }
    putFinancePayment(
        paymentId: number,
        financePaymentData: FinancePaymentData
    ): Observable<ResponseOneIf<FinancePaymentData>> {
        return this.http.put<ResponseOneIf<FinancePaymentData>>(
            `${environment.apiUrl}/financial-management/finace-payment/${paymentId}`,
            financePaymentData
        );
    }
    putFinancePaymentMemberReceiptViewFlag(
        paymentId: number,
        financePaymentData: FinancePaymentData
    ): Observable<ResponseOneIf<FinancePaymentData>> {
        return this.http.put<ResponseOneIf<FinancePaymentData>>(
            `${environment.apiUrl}/financial-management/finace-payment/member-receipt-view-flag/${paymentId}`,
            financePaymentData
        );
    }
    putFinanceImportLog(
        impId: number,
        financeImportLogData: FinanceImportLogData
    ): Observable<ResponseOneIf<FinanceImportLogData>> {
        return this.http.put<ResponseOneIf<FinanceImportLogData>>(
            `${environment.apiUrl}/financial-management/finace-import-log/${impId}`,
            financeImportLogData
        );
    }
    postTmpFinanceImportLog(
        tmpFinanceImportLogData: TmpFinanceImportLogData
    ): Observable<ResponseOneIf<TmpFinanceImportLogData>> {
        return this.http.post<ResponseOneIf<TmpFinanceImportLogData>>(
            `${environment.apiUrl}/financial-management/tmp-finance-import-log`,
            tmpFinanceImportLogData
        );
    }
    postTmpFinanceImportDetail(
        tmpFinanceImportDetailData: TmpFinanceImportDetailData
    ): Observable<ResponseOneIf<TmpFinanceImportDetailData>> {
        return this.http.post<ResponseOneIf<TmpFinanceImportDetailData>>(
            `${environment.apiUrl}/financial-management/tmp-finance-import-detail`,
            tmpFinanceImportDetailData
        );
    }
    findTmpFinanceImportLog(
        tmpFinanceImportLogData: TmpFinanceImportLogData
    ): Observable<ResponseListIf<TmpFinanceImportLogData>> {
        return this.http.post<ResponseListIf<TmpFinanceImportLogData>>(
            `${environment.apiUrl}/financial-management/find-tmp-finance-import-log`,
            tmpFinanceImportLogData
        );
    }
    findTmpFinanceImportDetail(
        tmpFinanceImportDetailData: TmpFinanceImportDetailData
    ): Observable<ResponseListIf<TmpFinanceImportDetailData>> {
        return this.http.post<ResponseListIf<TmpFinanceImportDetailData>>(
            `${environment.apiUrl}/financial-management/find-tmp-finance-import-detail`,
            tmpFinanceImportDetailData
        );
    }
    findFinanceReceiptConfig(
        financeReceiptConfigData: FinanceReceiptConfigData
    ): Observable<ResponseListIf<FinanceReceiptConfigData>> {
        return this.http.post<ResponseListIf<FinanceReceiptConfigData>>(
            `${environment.apiUrl}/financial-management/find-finance-receipt-config`,
            financeReceiptConfigData
        );
    }
    findFinancePayment(financePaymentData: FinancePaymentData): Observable<ResponseListIf<FinancePaymentData>> {
        return this.http.post<ResponseListIf<FinancePaymentData>>(
            `${environment.apiUrl}/financial-management/find-finance-payment`,
            financePaymentData
        );
    }
    findFinanceImportLog(financeImportLogData: FinanceImportLogData): Observable<ResponseListIf<FinanceImportLogData>> {
        return this.http.post<ResponseListIf<FinanceImportLogData>>(
            `${environment.apiUrl}/financial-management/find-finance-import-log`,
            financeImportLogData
        );
    }
    findFinanceImportDetail(
        financeImportDetailData: FinanceImportDetailData
    ): Observable<ResponseListIf<FinanceImportDetailData>> {
        return this.http.post<ResponseListIf<FinanceImportDetailData>>(
            `${environment.apiUrl}/financial-management/find-finance-import-detail`,
            financeImportDetailData
        );
    }
    postFinanceReceiptConfig(
        financeReceiptConfigData: FinanceReceiptConfigData
    ): Observable<ResponseOneIf<FinanceReceiptConfigData>> {
        return this.http.post<ResponseOneIf<FinanceReceiptConfigData>>(
            `${environment.apiUrl}/financial-management/finance-receipt-config`,
            financeReceiptConfigData
        );
    }
    postFinancePayment(financePaymentData: FinancePaymentData): Observable<ResponseOneIf<FinancePaymentData>> {
        return this.http.post<ResponseOneIf<FinancePaymentData>>(
            `${environment.apiUrl}/financial-management/finance-payment`,
            financePaymentData
        );
    }
    postFinanceImportLog(financeImportLogData: FinanceImportLogData): Observable<ResponseOneIf<FinanceImportLogData>> {
        return this.http.post<ResponseOneIf<FinanceImportLogData>>(
            `${environment.apiUrl}/financial-management/finance-import-log`,
            financeImportLogData
        );
    }
    postFinanceImportDetail(
        financeImportDetailData: FinanceImportDetailData
    ): Observable<ResponseOneIf<FinanceImportDetailData>> {
        return this.http.post<ResponseOneIf<FinanceImportDetailData>>(
            `${environment.apiUrl}/financial-management/finance-import-detail`,
            financeImportDetailData
        );
    }
    getFinancePayment(paymentId: number): Observable<ResponseOneIf<FinancePaymentData>> {
        return this.http.get<ResponseOneIf<FinancePaymentData>>(
            `${environment.apiUrl}/financial-management/finance-payment/${paymentId}`
        );
    }
    getFinanceImportLog(impId: number): Observable<ResponseOneIf<FinanceImportLogData>> {
        return this.http.get<ResponseOneIf<FinanceImportLogData>>(
            `${environment.apiUrl}/financial-management/finance-import-log/${impId}`
        );
    }
    putFinancePaymentVoid(
        paymentId: number,
        cancelReceiptSelected: any
    ): Observable<ResponseOneIf<FinancePaymentData>> {
        return this.http.put<ResponseOneIf<FinancePaymentData>>(
            `${environment.apiUrl}/financial-management/finace-payment/void/${paymentId}`,
            cancelReceiptSelected
        );
    }
}
