/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { LoginFormData, ResponseLoginData } from '../models/login';
import { environment } from 'src/environments/environment';
import { ResponseOneIf } from '../models/common';

@Injectable({ providedIn: 'root' })
export class LoginService {
    constructor(private http: HttpClient) {}

    login(loginFormData: LoginFormData): Observable<ResponseOneIf<ResponseLoginData>> {
        return this.http.post<ResponseOneIf<ResponseLoginData>>(
            `${environment.apiUrl}/login/authentication`,
            loginFormData
        );
    }

}
