/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { ResponseOneIf, UploadFileData } from '../models/common';
import { environment } from 'src/environments/environment';

@Injectable({ providedIn: 'root' })
export class PreviewFileService {

    constructor(private http: HttpClient) {}

    postFile(uploadFileData: UploadFileData): Observable<ResponseOneIf<UploadFileData>> {
        return this.http.post<ResponseOneIf<UploadFileData>>(`${environment.apiUrl}/preview/file`, uploadFileData);
    }
}
